<%@ Page Title="" Language="C#" MasterPageFile="~/master/application-detail.master" AutoEventWireup="true" CodeFile="cat710gplussftp.aspx.cs" Inherits="cat710gplussftp" %>

<asp:Content ID="Content1" ContentPlaceHolderID="DocTitleKeywords" Runat="Server">
    <title>CAT7 10GS S/FTP網路線-日進電線</title>
    <meta name="description" content="CAT7 10GS S/FTP 網路線,最新型的傳輸線，擁有市面上LAN CABLE中最快速的傳輸速度">	
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="JavaScriptCode" Runat="Server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="smallPicArea" Runat="Server">
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="largePicArea1" Runat="Server">
    <asp:Image ID="Image1" runat="server" ImageUrl="~/images/service_pic/cat6a-10gs-ftp-3.jpg" AlternateText="CAT7 10GS S/FTP網路線" />
</asp:Content>
<asp:Content ID="Content5" ContentPlaceHolderID="largePicArea2" Runat="Server">
    <asp:Image ID="Image2" runat="server" ImageUrl="~/images/service_pic/cat6a-10gs-ftp-4.jpg" AlternateText="CAT7 10GS S/FTP網路線" />
</asp:Content>
<asp:Content ID="Content6" ContentPlaceHolderID="largePicArea3" Runat="Server">
</asp:Content>
<asp:Content ID="Content7" ContentPlaceHolderID="prdTitle" Runat="Server">
    網路線<br />
    CAT7 10G-PLUS S/FTP Cable
</asp:Content>
<asp:Content ID="Content8" ContentPlaceHolderID="titleRowLink" Runat="Server">
</asp:Content>
<asp:Content ID="Content9" ContentPlaceHolderID="briefDescription" Runat="Server">
    <div class="subtitle">
        應用範圍
    </div>
    <table>
        <tr>
            <td>CAT7 10GS S/FTP 網路線,最新型的傳輸線，擁有市面上LAN CABLE中最快速的傳輸速度</td>
        </tr>
    </table>
    <div class="subtitle">
        技術資料
    </div>
    <table>
        <tr>
            <td>導體:</td>
            <td>23AWG 單芯/26AWG 多芯 裸銅</td>
        </tr>
        <tr>
            <td>絕緣:</td>
            <td>Foamskin PE</td>
        </tr>
        <tr>
            <td>隔離:</td>
            <td>AL-Polyester、編織銅網</td>
        </tr>
        <tr>
            <td>外被:</td>
            <td>LSZH</td>
        </tr>
        <tr>
            <td>阻抗:</td>
            <td>100±5&Omega;</td>
        </tr>
    </table>
</asp:Content>
<asp:Content ID="Content10" ContentPlaceHolderID="detailDescription" Runat="Server">
    <div class="subtitle">
        CAT7 10GS S/FTP網路線 產品規格表
    </div>
    <div class="content">
        <table>
            	<tr>
                	<td colspan="4">CABLE DATA</td>
                </tr>
            	<tr>
               	  <td>TYPE</td>
                    <td>PRODUCT NO.</td>
                    <td>DIAMETER<br />(mm/inch)</td>
                    <td>FLAME RATING</td>
                </tr>
                <tr>
                	<td>SOLID</td>
                    <td>TCL2304A01</td>
                    <td>8.0/0.314</td>
                    <td>LSZH</td>
                </tr>
              <tr>
               	<td>STRANDED</td>
                    <td>TBL2604A01</td>
                    <td>6.3/0.247</td>
                    <td>LSZH</td>
                </tr>
            </table>
        <table>
            	<tr>
					<td colspan="10">ELECTRICAL CHARACTERISTICS</td>
                </tr>
            	<tr>
                	<td>TYPE</td>
                	<td>FREQUENCY<br />(MHz)</td>
                    <td>INS LOSS<br />(dB/100m)<br />max</td>
                    <td>NEXT<br />(dB)<br />min</td>
                    <td>ACR<br />(dB)<br />min</td>
                    <td>PS NEXT<br />(dB)<br />min</td>
                    <td>PS ACR<br />(dB)<br />min</td>
                    <td>ACRF<br />(dB/100m)<br />min</td>
                    <td>PS ACRF<br />(dB/100m)<br />min</td>
                    <td>RETURN LOSS<br />(dB)<br />min</td>
                </tr>
                <tr>
                	<td rowspan="15">SOLID</td>
                    <td>1</td>
                    <td>1.96</td>
                    <td>80</td>
                    <td>78.04</td>
                    <td>77</td>
                    <td>75.04</td>
                    <td>80</td>
                    <td>77</td>
                    <td>20</td>
                </tr>
                <tr>
                  <td>4</td>
                  <td>3.64</td>
                  <td>80</td>
                  <td>76.36</td>
                  <td>77</td>
                  <td>73.36</td>
                  <td>80</td>
                  <td>77</td>
                  <td>23.01</td>
                </tr>
                <tr>
                  <td>10</td>
                  <td>5.7</td>
                  <td>80</td>
                  <td>74.3</td>
                  <td>77</td>
                  <td>71.3</td>
                  <td>74</td>
                  <td>71</td>
                  <td>25</td>
                </tr>
                <tr>
                  <td>20</td>
                  <td>8.07</td>
                  <td>80</td>
                  <td>71.93</td>
                  <td>77</td>
                  <td>68.93</td>
                  <td>67.98</td>
                  <td>64.98</td>
                  <td>25</td>
                </tr>
                <tr>
                  <td>31.25</td>
                  <td>10.13</td>
                  <td>80</td>
                  <td>69.87</td>
                  <td>77</td>
                  <td>66.87</td>
                  <td>64.1</td>
                  <td>61.1</td>
                  <td>23.64</td>
                </tr>
                <tr>
                  <td>62.5</td>
                  <td>14.49</td>
                  <td>75.46</td>
                  <td>60.97</td>
                  <td>72.46</td>
                  <td>57.97</td>
                  <td>58.08</td>
                  <td>55.08</td>
                  <td>21.54</td>
                </tr>
                <tr>
                  <td>100</td>
                  <td>18.52</td>
                  <td>72.4</td>
                  <td>53.88</td>
                  <td>69.4</td>
                  <td>50.88</td>
                  <td>54</td>
                  <td>51</td>
                  <td>20.11</td>
                </tr>
                <tr>
                  <td>155</td>
                  <td>23.35</td>
                  <td>69.55</td>
                  <td>46.2</td>
                  <td>66.55</td>
                  <td>43.2</td>
                  <td>50.19</td>
                  <td>47.19</td>
                  <td>18.77</td>
                </tr>
                <tr>
                  <td>200</td>
                  <td>26.76</td>
                  <td>67.88</td>
                  <td>41.12</td>
                  <td>64.88</td>
                  <td>38.12</td>
                  <td>47.98</td>
                  <td>44.98</td>
                  <td>18</td>
                </tr>
                <tr>
                  <td>250</td>
                  <td>30.18</td>
                  <td>66.43</td>
                  <td>36.25</td>
                  <td>63.43</td>
                  <td>33.25</td>
                  <td>46.04</td>
                  <td>43.04</td>
                  <td>17.3</td>
                </tr>
                <tr>
                  <td>300</td>
                  <td>33.32</td>
                  <td>65.24</td>
                  <td>31.92</td>
                  <td>62.24</td>
                  <td>28.92</td>
                  <td>44.46</td>
                  <td>41.46</td>
                  <td>17.3</td>
                </tr>
                <tr>
                  <td>350</td>
                  <td>36.25</td>
                  <td>64.24</td>
                  <td>27.99</td>
                  <td>61.24</td>
                  <td>24.99</td>
                  <td>43.12</td>
                  <td>40.12</td>
                  <td>17.3</td>
                </tr>
                <tr>
                  <td>400</td>
                  <td>39.01</td>
                  <td>63.37</td>
                  <td>24.36</td>
                  <td>60.37</td>
                  <td>21.36</td>
                  <td>41.96</td>
                  <td>38.96</td>
                  <td>17.3</td>
                </tr>
                <tr>
                  <td>500</td>
                  <td>44.14</td>
                  <td>61.92</td>
                  <td>17.78</td>
                  <td>58.92</td>
                  <td>14.78</td>
                  <td>40.02</td>
                  <td>37.02</td>
                  <td>17.3</td>
                </tr>
                <tr>
                  <td>600</td>
                  <td>48.87</td>
                  <td>60.73</td>
                  <td>11.86</td>
                  <td>57.73</td>
                  <td>8.86</td>
                  <td>38.44</td>
                  <td>35.44</td>
                  <td>17.3</td>
                </tr>
                <tr>
                	<td rowspan="15">STRANDED</td>
                    <td>1</td>
                    <td>2.94</td>
                    <td>80</td>
                    <td>77.06</td>
                    <td>77</td>
                    <td>74.06</td>
                    <td>80</td>
                    <td>77</td>
                    <td>20</td>
                </tr>
                <tr>
                  <td>4</td>
                  <td>5.46</td>
                  <td>80</td>
                  <td>74.54</td>
                  <td>77</td>
                  <td>71.54</td>
                  <td>80</td>
                  <td>77</td>
                  <td>23.01</td>
                </tr>
                <tr>
                  <td>10</td>
                  <td>8.55</td>
                  <td>80</td>
                  <td>71.45</td>
                  <td>77</td>
                  <td>68.45</td>
                  <td>74</td>
                  <td>71</td>
                  <td>25</td>
                </tr>
                <tr>
                  <td>20</td>
                  <td>12.11</td>
                  <td>80</td>
                  <td>67.89</td>
                  <td>77</td>
                  <td>64.89</td>
                  <td>67.98</td>
                  <td>64.98</td>
                  <td>25</td>
                </tr>
                <tr>
                  <td>31.25</td>
                  <td>15.2</td>
                  <td>80</td>
                  <td>64.8</td>
                  <td>77</td>
                  <td>61.8</td>
                  <td>64.1</td>
                  <td>61.1</td>
                  <td>23.64</td>
                </tr>
                <tr>
                  <td>62.5</td>
                  <td>21.73</td>
                  <td>75.46</td>
                  <td>53.73</td>
                  <td>72.46</td>
                  <td>50.73</td>
                  <td>58.08</td>
                  <td>55.08</td>
                  <td>21.54</td>
                </tr>
                <tr>
                  <td>100</td>
                  <td>27.78</td>
                  <td>72.4</td>
                  <td>44.62</td>
                  <td>69.4</td>
                  <td>41.62</td>
                  <td>54</td>
                  <td>51</td>
                  <td>20.11</td>
                </tr>
                <tr>
                  <td>155</td>
                  <td>35.03</td>
                  <td>69.55</td>
                  <td>34.52</td>
                  <td>66.55</td>
                  <td>31.52</td>
                  <td>50.19</td>
                  <td>47.19</td>
                  <td>18.77</td>
                </tr>
                <tr>
                  <td>200</td>
                  <td>40.14</td>
                  <td>67.88</td>
                  <td>27.74</td>
                  <td>64.88</td>
                  <td>24.74</td>
                  <td>47.98</td>
                  <td>44.98</td>
                  <td>18</td>
                </tr>
                <tr>
                  <td>250</td>
                  <td>45.27</td>
                  <td>66.43</td>
                  <td>21.16</td>
                  <td>63.43</td>
                  <td>18.16</td>
                  <td>46.04</td>
                  <td>43.04</td>
                  <td>17.3</td>
                </tr>
                <tr>
                  <td>300</td>
                  <td>49.98</td>
                  <td>65.24</td>
                  <td>15.26</td>
                  <td>62.24</td>
                  <td>12.26</td>
                  <td>44.46</td>
                  <td>41.46</td>
                  <td>17.3</td>
                </tr>
                <tr>
                  <td>350</td>
                  <td>54.38</td>
                  <td>64.24</td>
                  <td>9.86</td>
                  <td>61.24</td>
                  <td>6.86</td>
                  <td>43.12</td>
                  <td>40.12</td>
                  <td>17.3</td>
                </tr>
                <tr>
                  <td>400</td>
                  <td>58.52</td>
                  <td>63.37</td>
                  <td>4.85</td>
                  <td>60.37</td>
                  <td>1.85</td>
                  <td>41.96</td>
                  <td>38.96</td>
                  <td>17.3</td>
                </tr>
                <tr>
                  <td>500</td>
                  <td>66.21</td>
                  <td>61.92</td>
                  <td>NA</td>
                  <td>58.92</td>
                  <td>NA</td>
                  <td>40.02</td>
                  <td>37.02</td>
                  <td>17.3</td>
                </tr>
                <tr>
                  <td>600</td>
                  <td>73.31</td>
                  <td>60.73</td>
                  <td>NA</td>
                  <td>57.73</td>
                  <td>NA</td>
                  <td>38.44</td>
                  <td>35.44</td>
                  <td>17.3</td>
                </tr>
            </table>
    </div>
</asp:Content>

